# Generated by Django 4.2.7 on 2023-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_descriptio',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='توضیحات کوتاه'),
        ),
    ]
