# Generated by Django 4.2.7 on 2023-12-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_File',
        ),
    ]
