# Generated by Django 4.2.7 on 2023-12-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_product_base_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تایید / عدم تایید'),
        ),
    ]
