# Generated by Django 4.2.7 on 2023-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productcomment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='تایید / عدم تایید'),
        ),
    ]
