# Generated by Django 4.2.7 on 2024-01-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_productcomment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='product_module.producttag', verbose_name=' تگ ها'),
            preserve_default=False,
        ),
    ]
