# Generated by Django 4.2.7 on 2024-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_remove_producttag_product_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='product_module.producttag', verbose_name='دسته بندی ها'),
        ),
    ]
