# Generated by Django 4.2.7 on 2024-01-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_product_tag_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
