# Generated by Django 4.2.7 on 2024-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_remove_product_tag_delete_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
    ]
