# Generated by Django 4.2.7 on 2024-01-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=models.CharField(db_index=True, max_length=250, verbose_name='عنوان'), max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
    ]
