# Generated by Django 4.2.7 on 2024-01-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=True, verbose_name='حذف شده / نشده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
    ]
