# Generated by Django 4.2.7 on 2023-12-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تایید / عدم تایید'),
        ),
    ]
