# Generated by Django 4.2.7 on 2023-12-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0002_articlecomment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='تایید / عدم تایید'),
        ),
    ]
