# Generated by Django 4.2.7 on 2023-12-31 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0003_alter_articlecomment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticaleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coption', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('is_activ', models.BooleanField(verbose_name='فعال /غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='artical_modul.article')),
            ],
            options={
                'verbose_name': 'تگ مقاله',
                'verbose_name_plural': 'تگ های مقاله',
            },
        ),
    ]
