# Generated by Django 4.2.7 on 2024-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0004_articaletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=50, verbose_name='توضیحات کوتاه'),
        ),
    ]
