# Generated by Django 4.2.7 on 2024-01-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0005_alter_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=100, verbose_name='توضیحات کوتاه'),
        ),
    ]
