# Generated by Django 4.2.7 on 2024-01-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0006_alter_article_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articaletag',
            name='artical',
        ),
        migrations.AddField(
            model_name='articaletag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True, verbose_name='عنوتن url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='artical_modul.articaletag', verbose_name='تگ ها'),
        ),
    ]
