# Generated by Django 4.2.7 on 2024-01-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical_modul', '0007_remove_articaletag_artical_articaletag_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(related_name='articales', to='artical_modul.articlecategory', verbose_name='دسته بندی ها'),
        ),
    ]
